package shared;

public enum ServerBefehl {
    ANMELDEN,
    REGISTRIEREN,
    SEND_TEXT_MESSAGE,
    GET_USER_LIST,
    GET_MESSAGES_FROM,
    SET_PASSWORD,
    TEXT_MESSAGE,
    PDF_MESSAGE,
    SET_NICKNAME,
    FEEDBACK,
    GET_GROUPS,
    ABMELDEN, RECEIVE_MESSAGES_FROM, RECEIVE_GROUPS, RECEIVE_USER_LIST_OF_GROUP, GET_ALL_NICKNAMES, RECEIVE_NICKNAME_LIST, ANMELDEN_ERFOLGREICH,

    RAUM_ERSTELLEN,
    RAUMNAME_AENDERN,
    RAUM_LOESCHEN,
    VERWARNEN,
    KICKEN,
    BANNEN,
    PICTURE_MESSAGE, RECEIVE_COMPLETE_USER_LIST, PRIVATE_GROUP_LIST, REQUEST_PRIVATE_CHAT, REMOVE_PRIVATE_CHAT, VERBINDUNG_STARTEN, SERVERNAME_SETZEN
}
