package shared;

public enum ServerBefehl {
    ANMELDEN,
    REGISTRIEREN,
    SEND_TEXT_MESSAGE,
    GET_USER_LIST,
    GET_MESSAGES_FROM,
    SET_PASSWORD,
    TEXT_MESSAGE,
    SET_NICKNAME,
    FEEDBACK,
    GET_GROUPS,
    ABMELDEN, RECEIVE_MESSAGES_FROM, RECEIVE_GROUPS, RECEIVE_USER_LIST, GET_ALL_NICKNAMES, RECEIVE_NICKNAME_LIST, ANMELDEN_ERFOLGREICH
}
